In [6]:
from skimage import data
import cv2 as cv
import numpy as np

In [26]:
img=data.chelsea()
kernel=np.ones((3,3), np.float32)/7
#kernel=np.zeros((3,3),np.float32)   # all black

print(kernel)

filter=cv.filter2D(img,-1,kernel)
cv.imshow("Image",img)
cv.imshow("Filtered image",filter)
cv.waitKey()
cv.destroyAllWindows()

[[0.14285715 0.14285715 0.14285715]
 [0.14285715 0.14285715 0.14285715]
 [0.14285715 0.14285715 0.14285715]]
